language: c

sudo: false

addons: 
   apt: 
      packages: 
         - lcov
         - cppcheck

install:
  - git clone https://github.com/ThrowTheSwitch/Unity.git
  - git clone --recursive https://github.com/throwtheswitch/cmock.git
  - cd cmock
  - bundle install # Ensures you have all RubyGems needed
  - bundle exec rake # Run all CMock library tests
  - cd ..
script: make tests
